'use strict';

const mongoose = require('mongoose');

const { Schema } = mongoose;

const TaskSchema = new Schema(
  {
    weddingId:         { type: Schema.Types.ObjectId, ref: 'Wedding', required: true },
    title:             { type: String, required: true, trim: true },
    category:          {
      type: String,
      enum: ['bureaucracy', 'vendors', 'attire', 'logistics', 'extras'],
      required: true,
    },
    // Offset used when auto-generating from template (e.g., -180 = 6 months before)
    daysBeforeWedding: { type: Number, default: null },
    // Calculated absolute due date: weddingDate - daysBeforeWedding
    dueDate:           { type: Date, default: null },
    isDone:            { type: Boolean, default: false },
    isAutoGenerated:   { type: Boolean, default: false },
  },
  { timestamps: true }
);

TaskSchema.index({ weddingId: 1, isDone: 1 });
TaskSchema.index({ weddingId: 1, dueDate: 1 });

module.exports = mongoose.model('Task', TaskSchema);
