'use strict';

const express = require('express');
const auth = require('../middleware/auth');
const validate = require('../middleware/validate');
const { createTaskSchema, updateTaskSchema } = require('../validators/task.validator');
const Task = require('../models/Task');
const Budget = require('../models/Budget');
const Wedding = require('../models/Wedding');

const router = express.Router();
router.use(auth);

function envelopeDueDate(weddingDate) {
  const dueDate = new Date(weddingDate);
  dueDate.setDate(dueDate.getDate() - 3);
  return dueDate;
}

// Mirror of frontend isPaymentTask() — covers legacy records that predate requiresPayment field
function isPaymentTask(task) {
  return task.requiresPayment === true || task.category === 'vendors' || task.category === 'attire';
}

async function syncPaymentArtifacts(task) {
  if (!isPaymentTask(task)) return task;

  const paidAmount = task.paidAmount || 0;
  const remainingCashDue = task.remainingCashDue || 0;

  if (paidAmount > 0 || remainingCashDue > 0) {
    const budgetPayload = {
      category: task.title,
      vendorName: task.title,
      linkedTaskId: task._id,
      plannedCost: paidAmount + remainingCashDue,
      actualCost: paidAmount,
      advancePaid: paidAmount,
      // Cash due from task maps directly to remaining cash breakdown in budget
      remainingCashAmount: remainingCashDue,
      remainingCreditAmount: 0,
      remainingBankTransferAmount: 0,
      isDeleted: false,
      deletedAt: null,
    };

    const budgetEntry = await Budget.findOneAndUpdate(
      { weddingId: task.weddingId, linkedTaskId: task._id },
      { $set: budgetPayload },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );

    task.linkedBudgetEntryId = budgetEntry._id;
  } else if (task.linkedBudgetEntryId) {
    await Budget.findOneAndUpdate(
      { _id: task.linkedBudgetEntryId, weddingId: task.weddingId },
      { $set: { isDeleted: true, deletedAt: new Date() } },
    );
    task.linkedBudgetEntryId = null;
  }

  if (remainingCashDue > 0) {
    const wedding = await Wedding.findById(task.weddingId).select('weddingDate').lean();
    if (wedding?.weddingDate) {
      const envelopeTask = await Task.findOneAndUpdate(
        { weddingId: task.weddingId, linkedVendorTaskId: task._id },
        {
          $set: {
            title: `להכין מעטפה עבור ${task.title}`,
            category: 'logistics',
            dueDate: envelopeDueDate(wedding.weddingDate),
            isAutoGenerated: true,
            isDone: false,
          },
        },
        { upsert: true, new: true, setDefaultsOnInsert: true },
      );
      task.linkedVendorTaskId = envelopeTask._id;
    }
  } else if (task.linkedVendorTaskId) {
    await Task.findOneAndDelete({ _id: task.linkedVendorTaskId, weddingId: task.weddingId, isAutoGenerated: true });
    task.linkedVendorTaskId = null;
  }

  await task.save();
  return task;
}

// GET /api/tasks
router.get('/', async (req, res, next) => {
  try {
    const tasks = await Task.find({ weddingId: req.weddingId }).sort({ dueDate: 1 });
    res.json(tasks);
  } catch (err) { next(err); }
});

// POST /api/tasks
router.post('/', validate(createTaskSchema), async (req, res, next) => {
  try {
    const data = { ...req.body, weddingId: req.weddingId };
    if (data.dueDate) data.dueDate = new Date(data.dueDate);
    const task = await Task.create(data);
    await syncPaymentArtifacts(task);
    res.status(201).json(task);
  } catch (err) { next(err); }
});

// PATCH /api/tasks/:id
router.patch('/:id', validate(updateTaskSchema), async (req, res, next) => {
  try {
    const updates = { ...req.body };
    if (updates.dueDate) updates.dueDate = new Date(updates.dueDate);

    const task = await Task.findOneAndUpdate(
      { _id: req.params.id, weddingId: req.weddingId },
      { $set: updates },
      { new: true }
    );
    if (!task) return res.status(404).json({ message: 'Task not found' });
    if (task.isDone && isPaymentTask(task) && !(task.paidAmount > 0)) {
      return res.status(400).json({ message: 'כדי לסמן משימה זו כבוצעת צריך להזין כמה שולם' });
    }
    await syncPaymentArtifacts(task);
    res.json(task);
  } catch (err) { next(err); }
});

// DELETE /api/tasks/:id — hard delete (tasks have no audit requirement)
router.delete('/:id', async (req, res, next) => {
  try {
    const task = await Task.findOne({ _id: req.params.id, weddingId: req.weddingId });
    if (!task) return res.status(404).json({ message: 'Task not found' });
    if (task.linkedBudgetEntryId) {
      await Budget.findOneAndUpdate(
        { _id: task.linkedBudgetEntryId, weddingId: req.weddingId },
        { $set: { isDeleted: true, deletedAt: new Date() } },
      );
    }
    if (task.linkedVendorTaskId) {
      await Task.findOneAndDelete({ _id: task.linkedVendorTaskId, weddingId: req.weddingId, isAutoGenerated: true });
    }
    await Task.findOneAndDelete({ _id: req.params.id, weddingId: req.weddingId });
    res.json({ message: 'Task deleted' });
  } catch (err) { next(err); }
});

module.exports = router;
