export type Wedding = {
  _id?: string;
  id?: string;
  coupleName: string;
  weddingDate: string;
  venue?: string;
  globalBudget?: number;
};

export type Invitation = {
  _id: string;
  householdName: string;
  whatsappNumber?: string | null;
  rsvpStatus: 'pending' | 'going' | 'not_going' | 'maybe';
  giftAmount?: number;
  side: 'groom' | 'bride' | 'mutual';
  group: 'family' | 'friends' | 'work' | 'other';
  rsvpToken?: string;
};

export type Guest = {
  _id: string;
  invitationId: string;
  firstName: string;
  lastName?: string;
  mealPreference: 'meat' | 'chicken' | 'vegan' | 'kids' | 'none';
  assignedTableId?: string | null;
  age?: number | null;
  notes?: string;
};

export type Task = {
  _id: string;
  title: string;
  category: 'bureaucracy' | 'vendors' | 'attire' | 'logistics' | 'extras';
  dueDate?: string | null;
  isDone: boolean;
  isAutoGenerated?: boolean;
};

export type BudgetEntry = {
  _id: string;
  category: string;
  vendorName?: string;
  plannedCost: number;
  actualCost: number;
  advancePaid: number;
};

export type SeatingPlan = {
  tables: Array<{
    tableId: string;
    number: number;
    capacity: number;
    isKnight: boolean;
    side: string;
    assignedGuestIds: Array<{
      _id: string;
      firstName: string;
      lastName?: string;
      mealPreference?: string;
    }>;
  }>;
};

export type Warning = {
  type: string;
  message: string;
  count?: number;
  data?: Array<{ tableId: string; number: number }>;
};

export type AlcoholEstimate = {
  confirmedAdults: number;
  bufferPercent: number;
  beer_bottles: number;
  wine_bottles: number;
  vodka_bottles: number;
  whiskey_bottles: number;
  arak_bottles: number;
};
